# Generated by Django 4.2 on 2023-04-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedidoproductos',
            table='PedidoProductos',
        ),
    ]
