# Generated by Django 4.1.1 on 2023-04-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("last_name", models.CharField(blank=True, max_length=25, null=True)),
                ("email", models.CharField(max_length=25)),
                ("address", models.CharField(blank=True, max_length=25, null=True)),
                ("phone_number", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "Usuarios", "managed": False,},
        ),
        migrations.AlterModelTable(name="pedidoproductos", table="PedidoProductos",),
    ]
