# Generated by Django 4.2 on 2023-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpostal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
