# Generated by Django 4.1.4 on 2023-01-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_user_email_alter_user_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
    ]
