# Generated by Django 4.1.4 on 2023-01-31 18:19

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
