# Generated by Django 4.1.4 on 2023-02-05 16:34

from django.db import migrations, models
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
