# Generated by Django 4.1.5 on 2023-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albaranes',
            fields=[
                ('albaran_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('id_seguimiento', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Albaranes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_cost', models.FloatField()),
            ],
            options={
                'db_table': 'Pedido-Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_order', models.DateField()),
                ('total_cost', models.FloatField()),
                ('address', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('provprod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Proveedor-Producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False},
        ),
    ]
