# Generated by Django 4.1.5 on 2023-02-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_albaranes_estados_pedidoproductos_pedidos_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productos',
            table='Productos',
        ),
    ]
